config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "dashboards", to: "dashboards#index"
    resources :users, only: [:show, :destroy]
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  scope module: :public do
    devise_for :users
    root to: "homes#top"
    get "/about", to: "homes#about"
    get "/follow_feed", to: "posts#follow_feed"
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get "/mypage", to: "users#mypage"
    resources :users, only: [:show, :edit, :update, :destroy] do
      member do
        get :favorite_posts
      end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    get "/search", to: "searches#search"
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :index, :show]
    resources :notifications, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @user = User.find(current_user.id)
    @post = Post.new

    @model = params[:model]
    @word = params[:word]
    @method = params[:method]

    # 選択したモデルに応じて検索を実行
    if @model  == "user"
      @users = User.search_for(@word, @method)
      if @users.count > 0
        flash.now[:notice] = "新しい仲間との出会いがここに！どんなトレーニングをしているか見てみましょう💪"
      else
        flash.now[:alert] = "該当するユーザーが見つかりませんでした💡 条件を変更してみてください！"
      end
    else
      @posts = Post.search_for(@word, @method)
      if @posts.count > 0
        flash.now[:notice] = "みんなのトレーニング記録を発見！インスピレーションを受け取ろう🔥！"
      else
        flash.now[:alert] = "まだ誰もそのトピックについて投稿していないようです。ぜひあなたが最初の投稿を🚀！"
      end
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<% if user_signed_in? %>
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :word %>
    <%= f.select :model, options_for_select({"User" => "user", "Post" => "post"}) %>
    <%= f.select :method, options_for_select({"完全一致" => "perfect_match", "前方一致" => "forward_match", "後方一致" => "backward_match", "部分一致" => "partial_match"}) %>
    <%= f.submit "検索" %>
  <% end %>
<% end %>

app/views/searches/search.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-4">
      <h2 class="font-weight-bold mb-4">プロフィール</h2>
      <div class="card-list-container">
        <div class="card border border-info rounded-2 shadow-lg mb-4">
          <div class="card-body">
            <%= image_tag @user.get_profile_image(200,200),
            class:"rounded-circle img-fluid object-fit-cover mx-auto d-block shadow-sm mt-3" %>
            <h6 class="text-center py-4 border-bottom mx-auto d-block"><strong><%= @user.name %></strong></h6>
            <p class="card-text text-center py-3"><%= @user.status_message %></p>
          </div>
        </div>
      </div>
      <div class="row">
        <% if @user == current_user %>
          <%= link_to edit_user_path(@user.id), class: "btn btn-outline-info btn-block" do %>
            <i class="fas fa-user-cog"></i>プロフィール編集
          <% end %>
        <% end %>
      </div>
      <div class="shadow-lg rounded px-0 my-5 bg-white">
        <h5 class="text-white bg-emerald p-4 mb-0 rounded-top">投稿フォーム</h5>
        <div class="form-body p-4">
          <%= form_with model: @post, class: "mt-3" do |f| %>
            <div class="form-group">
              <h6 class="text-dark">フィットネスを行なった日</h6>
              <%= f.date_field :fitness_date, class: "form-control border-emerald" %>
            </div>
            <div class="form-group">
              <h6 class="text-dark">メニュー</h6>
              <%= f.text_area :menu, class: "form-control border-emerald", rows: 3, placeholder: "例：ランニング 5km、スクワット 3セット" %>
            </div>
            <div class="form-group">
              <h6 class="text-dark">感想・メモ</h6>
              <%= f.text_area :body, class: "form-control border-emerald", rows: 3, placeholder: "今日のフィットネスについて記録を残しましょう" %>
            </div>
            <div class="form-group">
              <h6 class="text-dark">画像(任意)</h6>
              <%= f.file_field :image, accept: "image/*", class: "form-control border-emerald" %>
            </div>
            <hr>
            <%= f.submit '投稿', class: "btn btn-lg btn-block btn-emerald text-white mt-4" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-7 offset-md-1">
      <% if @model == 'user' %>
        <h2 class="font-weight-bold mb-4">ユーザー <%= I18n.t("search.method.#{@method}", default: @method) %> 検索結果一覧</h2>
        <div class="card-list-container">
          <div class="row">
            <% @users.each do |user| %>
              <div class="col-md-6">
                <div class="card border border-info rounded-2 shadow-lg mb-4">
                  <%= link_to user_path(user.id) do %>
                    <div class="card-body">
                      <%= image_tag user.get_profile_image(150,150),
                      class:"rounded-circle img-fluid object-fit-cover mx-auto d-block shadow-sm mt-3" %>
                      <h6 class="text-center py-4 border-bottom mx-auto d-block text-dark"><strong><%= user.name %></strong></h6>
                      <p class="card-text text-center py-3 text-dark"><%= user.status_message %></p>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% elsif @model == 'post' %>
        <h2 class="font-weight-bold mb-4">投稿 <%= I18n.t("search.method.#{@method}", default: @method) %> 検索結果一覧</h2>
        <div class="card-list-container">
          <% @posts.each do |post| %>
            <div class="card shadow-lg border border-emerald rounded-2 mb-4">
              <div class="card-header d-flex align-items-center gap-3">
                <%= link_to image_tag(post.user.get_profile_image(30,30), class:"rounded-circle"), user_path(post.user.id) %>
                <%= link_to user_path(post.user.id) do %>
                  <h6 class="text-black"><%= post.user.name %></h6>
                <% end %>
                <%= link_to post_path(post.id) do %>
                  <p class="fs-6-50 text-black"><i class="far fa-clock clock-icon"></i><%= time_ago_in_words(post.created_at) %>前</p>
                <% end %>
              </div>
              <%= link_to post_path(post.id) do %>
                <div class="card-body">
                  <p class="card-text text-dark border-bottom"><strong>日付:</strong> <%= post.fitness_date.strftime("%Y年%m月%d日") %></p>
                  <p class="card-text text-dark border-bottom"><strong>メニュー:</strong> <%= post.menu %></p>
                  <p class="card-text text-dark border-bottom"><strong>感想・メモ:</strong> <%= post.body %></p>
                  <% if post.image.attached? %>
                    <%= image_tag post.get_image(200,200), class:"img-fluid object-fit-cover rounded-4 mx-auto d-block shadow-sm" %>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>