config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "dashboards", to: "dashboards#index"
    resources :users, only: [:show, :destroy]
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  scope module: :public do
    devise_for :users
    root to: "homes#top"
    get "/about", to: "homes#about"
    get "/follow_feed", to: "posts#follow_feed"
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get "/mypage", to: "users#mypage"
    resources :users, only: [:show, :edit, :update, :destroy] do
      member do
        get :favorite_posts
      end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    get "/search", to: "searches#search"
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :index, :show]
    resources :notifications, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy

  validates :start_time, presence: true
  validates :title, presence: true

  after_create do
    user.followers.each do |follower|
      notifications.create(user_id: follower.id)
    end
  end

  def self.search_for(word, method)
    if method == "perfect_match"
      Post.where("menu or body ", word, word)
    elsif method == "forward_match"
      Post.where("menu LIKE ? or body LIKE ?", word + "%", word + "%")
    elsif method == "backward_match"
      Post.where("menu LIKE ? or body LIKE ?", "%" + word, "%" + word)
    else
      Post.where("menu LIKE ? or body LIKE ?", "%" + word + "%", "%" + word + "%")
    end
  end

  def get_image(width, height)
    return nil unless image.attached?
    image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "投稿完了！あなたの努力がみんなのモチベーションに繋がります 🌟"
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:notice] = "投稿を削除しました！次の記録でまた頑張りましょう 💪✨"
    redirect_to posts_path
  end

  def index
    @user = current_user
    @post = Post.new
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "投稿を更新しました！新しい内容でモチベーションアップ 💪🔥"
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:fitness_date, :menu, :body, :image)
  end

  def is_matching_login_user
    post = Post.find(params[:id])
    unless post.user.id == current_user.id
      redirect_to posts_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<% if @post.errors.any? %>
  <div class="errormessage">
    投稿の編集に失敗しました 😢 入力内容をご確認ください。
    <h2><%= @post.errors.count %>件のエラーが発生しています</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="container">
  <div class="row g-0 justify-content-center">
    <div class="col-md-6 col-sm-10 shadow-lg rounded px-0 my-5 bg-white">
      <h5 class="text-white bg-emerald p-4 mb-0 rounded-top">編集フォーム</h5>
      <div class="form-body p-4">
        <%= form_with model: @post, class: "mt-3", method: :patch do |f| %>
          <div class="form-group">
            <h6 class="text-dark">フィットネスを行なった日</h6>
            <%= f.date_field :fitness_date, class: "form-control border-emerald" %>
          </div>
          <div class="form-group">
            <h6 class="text-dark">メニュー</h6>
            <%= f.text_area :menu, class: "form-control border-emerald", rows: 3, placeholder: "例：ランニング 5km、スクワット 3セット" %>
          </div>
          <div class="form-group">
            <h6 class="text-dark">感想・メモ</h6>
            <%= f.text_area :body, class: "form-control border-emerald", rows: 3, placeholder: "今日のフィットネスについて記録を残しましょう" %>
          </div>
          <div class="form-group">
            <h6 class="text-dark">画像(任意)</h6>
            <%= f.file_field :image, accept: "image/*", class: "form-control border-emerald" %>
          </div>
          <hr>
          <%= f.submit '保存', class: "btn btn-lg btn-block btn-emerald text-white mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-4">
      <h2 class="font-weight-bold mb-4">プロフィール</h2>
      <div class="card-list-container">
        <div class="card border border-info rounded-2 shadow-lg mb-4">
          <div class="card-body">
            <%= image_tag @user.get_profile_image(200,200),
            class:"rounded-circle img-fluid object-fit-cover mx-auto d-block shadow-sm mt-3" %>
            <h6 class="text-center py-4 border-bottom mx-auto d-block"><strong><%= @user.name %></strong></h6>
            <p class="card-text text-center py-3"><%= @user.status_message %></p>
          </div>
        </div>
      </div>
      <div class="row">
        <% if @user == current_user %>
          <%= link_to edit_user_path(@user.id), class: "btn btn-outline-info btn-block" do %>
            <i class="fas fa-user-cog"></i>プロフィール編集
          <% end %>
        <% end %>
      </div>
      <div class="shadow-lg rounded px-0 my-5 bg-white">
        <h5 class="text-white bg-emerald p-4 mb-0 rounded-top">投稿フォーム</h5>
        <div class="form-body p-4">
          <%= form_with model: @post, class: "mt-3" do |f| %>
            <div class="form-group">
              <h6 class="text-dark">フィットネスを行なった日</h6>
              <%= f.date_field :fitness_date, class: "form-control border-emerald" %>
            </div>
            <div class="form-group">
              <h6 class="text-dark">メニュー</h6>
              <%= f.text_area :menu, class: "form-control border-emerald", rows: 3, placeholder: "例：ランニング 5km、スクワット 3セット" %>
            </div>
            <div class="form-group">
              <h6 class="text-dark">感想・メモ</h6>
              <%= f.text_area :body, class: "form-control border-emerald", rows: 3, placeholder: "今日のフィットネスについて記録を残しましょう" %>
            </div>
            <div class="form-group">
              <h6 class="text-dark">画像(任意)</h6>
              <%= f.file_field :image, accept: "image/*", class: "form-control border-emerald" %>
            </div>
            <hr>
            <%= f.submit '投稿', class: "btn btn-lg btn-block btn-emerald text-white mt-4" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-7 offset-md-1">
      <h2 class="font-weight-bold mb-4">投稿一覧</h2>
      <div class="card-list-container">
        <% @posts.each do |post| %>
          <div class="card shadow-lg border border-emerald rounded-2 mb-4">
            <div class="card-header d-flex align-items-center gap-3">
              <%= link_to image_tag(post.user.get_profile_image(30,30), class:"rounded-circle"), user_path(post.user.id) %>
              <%= link_to user_path(post.user.id) do %>
                <h6 class="text-black"><%= post.user.name %></h6>
              <% end %>
              <%= link_to post_path(post.id) do %>
                <p class="fs-6-50 text-black"><i class="far fa-clock clock-icon"></i><%= time_ago_in_words(post.created_at) %>前</p>
              <% end %>
            </div>
            <%= link_to post_path(post.id) do %>
              <div class="card-body">
                <p class="card-text text-dark border-bottom"><strong>日付:</strong> <%= post.fitness_date.strftime("%Y年%m月%d日") %></p>
                <p class="card-text text-dark border-bottom"><strong>メニュー:</strong> <%= post.menu %></p>
                <p class="card-text text-dark border-bottom"><strong>感想・メモ:</strong> <%= post.body %></p>
                <% if post.image.attached? %>
                  <%= image_tag post.get_image(200,200), class:"img-fluid object-fit-cover rounded-4 mx-auto mb-3 d-block shadow-sm" %>
                <% end %>
                <p class="card-text text-dark border-bottom mb-1"><i class="fa-regular fa-comment"></i>コメント数 <%= @post.post_comments.count %></p>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <div class="errormessage">
    投稿に失敗しました。もう一度確認してください 🙇‍♂️
    <h2><%= @post.errors.count %>件のエラーが発生しています</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="container">
  <div class="row g-0 justify-content-center">
    <div class="col-md-6 col-sm-10 shadow-lg rounded px-0 my-5 bg-white">
      <h5 class="text-white bg-emerald p-4 mb-0 rounded-top">投稿フォーム</h5>
      <div class="form-body p-4">
        <%= form_with model: @post, class: "mt-3" do |f| %>
          <div class="form-group">
            <h6 class="text-dark">フィットネスを行なった日</h6>
            <%= f.date_field :fitness_date, class: "form-control border-emerald" %>
          </div>
          <div class="form-group">
            <h6 class="text-dark">メニュー</h6>
            <%= f.text_area :menu, class: "form-control border-emerald", rows: '3', placeholder: "例：ランニング 5km、スクワット 3セット" %>
          </div>
          <div class="form-group">
            <h6 class="text-dark">感想・メモ</h6>
            <%= f.text_area :body, class: "form-control border-emerald", rows: '3', placeholder: "今日のフィットネスについて記録を残しましょう" %>
          </div>
          <div class="form-group">
            <h6 class="text-dark">画像(任意)</h6>
            <%= f.file_field :image, accept: "image/*", class: "form-control border-emerald" %>
          </div>
          <hr>
          <%= f.submit '投稿', class: "btn btn-lg btn-block btn-emerald text-white mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-sm-12 col-md-8 mx-auto">
      <h2 class="font-weight-bold mb-4">投稿詳細</h2>
      <div class="card-list-container">
        <div class="card shadow-lg border border-emerald rounded-2 mb-4">
          <div class="card-header d-flex align-items-center gap-3">
            <%= link_to image_tag(@post.user.get_profile_image(30,30), class:"rounded-circle"), user_path(@post.user.id) %>
            <%= link_to user_path(@post.user.id) do %>
              <h6 class="text-black"><%= @post.user.name %></h6>
            <% end %>
            <p class="fs-6-50 text-black"><i class="far fa-clock clock-icon"></i><%= time_ago_in_words(@post.created_at) %>前</p>
            <% if @post.user == current_user %>
              <%= link_to "編集", edit_post_path(@post.id), class: "btn btn-sm btn-info ms-auto" %>
              <%= link_to "削除", post_path(@post), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に消しますか?" %>
            <% end %>
          </div>
          <div class="card-body">
            <p class="card-text text-dark border-bottom"><strong>日付:</strong> <%= @post.fitness_date.strftime("%Y年%m月%d日") %></p>
            <p class="card-text text-dark border-bottom"><strong>メニュー:</strong> <%= @post.menu %></p>
            <p class="card-text text-dark border-bottom"><strong>感想・メモ:</strong> <%= @post.body %></p>
            <% if @post.image.attached? %>
              <%= image_tag @post.get_image(300,300), class:"img-fluid object-fit-cover rounded-4 mx-auto mb-3 d-block shadow-sm" %>
            <% end %>
            <%= @post.created_at.strftime('%P') == 'am' ? '午前' : '午後' %>
            <%= @post.created_at.strftime('%l:%M・%Y年%m月%d日') %>
            <p class="card-text border-top border-bottom mb-3 pt-3"><i class="fa-regular fa-comment"></i>コメント数 <%= @post.post_comments.count %></p>
            <%= form_with model: [@post, @post_comment] do |f| %>
              <%= f.text_area :comment, class: "form-control", rows: '2', placeholder: "コメントをここに" %>
              <div class="d-flex">
                <%= f.submit "送信", class: "btn btn-sm btn-secondary ms-auto mt-2" %>
              </div>
            <% end %>
          </div>
          <% @post.post_comments.each do |post_comment| %>
            <div class="card-body border">
              <div class="d-flex align-items-center gap-3">
                <%= image_tag post_comment.user.get_profile_image(30,30), class:"rounded-circle" %>
                <h6><%= post_comment.user.name %></h6>
                <p class="fs-6-50"><i class="far fa-clock clock-icon"></i><%= time_ago_in_words(post_comment.created_at) %>前</p>
                <% if post_comment.user == current_user %>
                  <%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete, class: "btn btn-sm btn-danger ms-auto", "data-confirm" => "本当に消しますか?" %>
                <% end %>
              </div>
              <%= post_comment.comment %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>