config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "dashboards", to: "dashboards#index"
    resources :users, only: [:show, :destroy]
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  scope module: :public do
    devise_for :users
    root to: "homes#top"
    get "/about", to: "homes#about"
    get "/follow_feed", to: "posts#follow_feed"
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get "/mypage", to: "users#mypage"
    resources :users, only: [:show, :edit, :update, :destroy] do
      member do
        get :favorite_posts
      end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    get "/search", to: "searches#search"
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :index, :show]
    resources :notifications, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  layout "admin"
  def index
    @users = User.all.order(created_at: :desc).page(params[:page])
  end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/views/admin/dashboards/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-8">
      <h4 class="bg-secondary-subtle w-25 my-2 p-1">ユーザー管理</h4>
      <table class="table">
        <thead  class="table-light border-top-color border-secondary">
          <tr>
            <th scope="col">ユーザーID</th>
            <th scope="col">名前</th>
            <th scope="col">メールアドレス</th>
            <th scope="col">登録日時</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <th scope="row"><%= link_to user.id, admin_user_path(user.id), class: "text-dark" %></th>
              <td><%= link_to user.name, admin_user_path(user.id), class: "text-dark" %></td>
              <td><%= link_to user.email, admin_user_path(user.id), class: "text-dark" %></td>
              <td><%= link_to user.created_at.strftime("%Y年%m月%d日 %-H:%M"), admin_user_path(user.id), class: "text-dark" %></td>
              <% if user.email != "guest@example.com" %>
                <td><%= link_to '削除', admin_user_path(user), class: "btn btn-outline-danger btn-block", method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @users %>
    </div>
  </div>
</div>