config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "dashboards", to: "dashboards#index"
    resources :users, only: [:show, :destroy]
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  scope module: :public do
    devise_for :users
    root to: "homes#top"
    get "/about", to: "homes#about"
    get "/follow_feed", to: "posts#follow_feed"
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get "/mypage", to: "users#mypage"
    resources :users, only: [:show, :edit, :update, :destroy] do
      member do
        get :favorite_posts
      end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    get "/search", to: "searches#search"
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :index, :show]
    resources :notifications, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - Motivefit</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/bd90a16fee.js" crossorigin="anonymous"></script>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body class="d-flex flex-column vh-100">
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
      <div class="container">
        <a class="navbar-brand" href=""><%= image_tag "motivefit-logo.png", size: "250x50" %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown" style>
          <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li>
                <%= link_to admin_dashboards_path, class: "nav-link text-dark ml-1" do %>
                  <i class="fa-solid fa-clipboard-list"></i>
                  ダッシュボード
                <% end %>
              </li>
              <li>
                <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-dark ml-1" do %>
                  <i class="fa-solid fa-sign-out-alt"></i>
                  Log out
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to "/", class: "nav-link text-dark mx-1" do %>
                  <i class="fas fa-home"></i>
                  ホーム
                <% end %>
              </li>
              <li>
                <%= link_to about_path, class: "nav-link text-dark mx-1" do %>
                  <i class="fa-regular fa-lightbulb"></i>
                  このサイトについて
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class: "nav-link text-dark mx-1" do %>
                  <i class="fa-solid fa-user-plus"></i>
                  Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class: "nav-link text-dark ml-1" do %>
                  <i class="fa-solid fa-sign-in-alt"></i>
                  Log in
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main class="mb-auto">
  <%= yield %>
  </main>
  <footer class="bg-light text-dark pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-5">
            <p>仲間同士でお互いのやる気を引き出すSNS</p>
            <%= image_tag"motivefit-logo.png", size: "250x50" %>
          </div>
          <div class="col-md-7">
            <h6 class="text-dark mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-black-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-black-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Motivefit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/bd90a16fee.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container">
          <a class="navbar-brand" href="/"><%= image_tag "motivefit-logo.png", size: "250x50" %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown" style>
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to posts_path, class: "nav-link text-dark mx-1" do %>
                    <i class="fa-solid fa-list"></i>
                    投稿一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to mypage_path, class: "nav-link text-dark mx-1" do %>
                    <i class="fa-regular fa-user"></i>
                    マイページ
                  <% end %>
                </li>
                <li class="dropdown">
                  <button class="btn btn-outline-info dropdown-toggle rounded-4" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    通知
                    <span class="badge badge-danger rounded-4"><%= current_user.notifications.where(read: false).count %></span>
                  </button>
                  <div class="dropdown-menu rounded-4 overflow-auto" style="max-height: 300px;" aria-labelledby="dropdownMenuButton">
                    <% if current_user.notifications.where(read: false).any? %>
                      <small class="dropdown-item disabled">直近5件の未読の通知を表示しています</small>
                      <% current_user.notifications.where(read: false).limit(5).order(created_at: :desc).each do |notification| %>
                        <%= link_to notification_message(notification), notification_path(notification), method: :patch, class: "dropdown-item" %>
                      <% end %>
                    <% else %>
                      <span class="dropdown-item disabled">未読の通知はありません</span>
                    <% end %>
                  </div>
                </li>
                <li>
                  <%= link_to rooms_path, class: "nav-link text-dark mx-1" do %>
                    <i class="fa-regular fa-envelope"></i>
                    メッセージ
                  <% end %>
                </li>
                <li>
                  <%= link_to new_post_path, class: "nav-link text-emerald mx-1" do %>
                    <i class="fa-regular fa-pen-to-square"></i>
                    新規投稿
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-dark ml-1" do %>
                    <i class="fa-solid fa-sign-out-alt"></i>
                    Log out
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to "/", class: "nav-link text-dark mx-1" do %>
                    <i class="fa-solid fa-house"></i>
                    ホーム
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class: "nav-link text-dark mx-1" do %>
                    <i class="fa-regular fa-lightbulb"></i>
                    このサイトについて
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "nav-link text-dark mx-1" do %>
                    <i class="fa-solid fa-user-plus"></i>
                    Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "nav-link text-dark ml-1" do %>
                    <i class="fa-solid fa-sign-in-alt"></i>
                    Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <div class="d-flex justify-content-center mb-2">
        <%= render "public/searches/form" %>
      </div>
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    </main>
    <footer class="bg-light text-dark pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-5">
            <p>仲間同士でお互いのやる気を引き出すSNS</p>
            <%= image_tag"motivefit-logo.png", size: "250x50" %>
          </div>
          <div class="col-md-7">
            <h6 class="text-dark mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-black-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-black-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>